version: '2'

services:

# Snare service
  snare:
    build: .
    container_name: snare
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
      default:
        ipv4_address: 10.0.2.3
    image: "honeypot-server:latest"

networks:
  default:
    external: 
       name: main-overlay
