version: '2.0'

volumes:
  cowrie-etc:
  cowrie-var:

services:
  cowrie:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var
    networks:
      - default

networks:
  default:
    external: 
       name: main-overlay