version: '2'

services:

# Snare service
  snare:
    build: .
    container_name: snare
    restart: always
    stop_signal: SIGKILL
    tty: true
    networks:
     - default
    image: "mushorg/snare:latest"

networks:
  default:
    external: 
       name: main-overlay
